apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: event-bus
spec:
  rules:
    - host: event-bus-wrichter-dhbw-exercise-1.apps.osd-evalcluster.v0z2.p1.openshiftapps.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: event-bus
              servicePort: 4005
